# SPDX-License-Identifier: GPL-2.0

## e2000 test-a/b/c development board series.
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-test-a-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-test-b-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-test-c-board.dtb

dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-test-a-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-test-b-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-test-c-board.dtb

dtb-$(CONFIG_ARCH_PHYTIUM) += e2000s-test-a-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000s-test-b-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000s-test-c-board.dtb

## e2000 general demo development board series.
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-demo-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-demo-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000s-demo-board.dtb

## e2000 specific industry development board series.
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-miniitx-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-miniitx-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-vpx-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-edu-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-come-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-power-board.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-hanwei-board.dtb
